[package]
name = "Asaogea"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/*"
]
resolver = "2"

[dependencies]
core = {path = "crates/core"}
job-sys = {path = "crates/job-sys"}

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.89"

rayon = "1.10.0"