[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }

vulkanalia = { version = "0.25.0", features = ["window", "libloading"] }
winit = "0.30.5"
anyhow = "1.0.89"
tracing = "0.1.40"
